name: 'PHP Syntax Checker (Lint)'
description: 'php syntax control (php -l)'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  dir:
    description: 'Folder to check syntax'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/stuudium/actions-php-lint:7.4'
  args:
    - ${{ inputs.dir }}
